# Generated by Django 5.2.7 on 2025-10-31 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('yoga', 'Yoga'), ('breathing', 'Breathing Exercise'), ('music', 'Calming Music'), ('meditation', 'Meditation'), ('exercise', 'Physical Exercise')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('youtube_url', models.URLField()),
                ('bonus_points', models.IntegerField(default=10)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentalHealthAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_keywords', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High - Urgent'), ('critical', 'Critical - Immediate Action')], max_length=20)),
                ('context', models.TextField(help_text='Where was this detected')),
                ('message_content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doctor_notified', models.BooleanField(default=False)),
                ('institute_notified', models.BooleanField(default=False)),
                ('action_taken', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
